### ISSUE TITLE
Font used on screenshots

### ISSUE THREAD

**Issue by KevinBorjaLundero** [gantoreno/vscode-gabriel#1]
Hi! Which font is used on your vscode? Thanks

**Comment by gantoreno** [comment]
Hey Kevin! Sorry for the late reply, I'm using Google Sans Mono, a new font face Google started slowly introducing in their fonts website (https://fonts.google.com), you can see it when selecting a font:

![image](https://user-images.githubusercontent.com/43397475/138292474-1f792ba1-15ff-4756-a37e-d307693b4f63.png)

It's not easy to get, since it's a private font and not open to the public (see https://fonts.google.com/license/googlerestricted), it's also not listed on their website, and googling it does not appear to throw any relevant result. BUT, it is listed on their API endpoints:

```
https://fonts.googleapis.com/css?family=<family-name>:<variant>
```

Put that URL on your browser and replace `<family-name>` with `Google+Sans+Mono`, and `<variant>` with one of the following:

 - `400`
 - `400italic`
 - `500`
 - `500italic`
 - `600`
 - `600italic`
 - `700`
 - `700italic`

For each one, grab the URL inside the `src` attribute from the `@font-face` declaration, and paste it into your browser, it should download a web font file (`.woff`), then you just have to convert that file into a `.ttf` (I used https://convertio.co/es/woff-ttf/), and there you have it! Do this for each variant, and you'll have this awesome font.

Hope this helps! And thank you for using my theme. :)
